/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupportIndexRouteImport } from './routes/support/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as BlogAllRouteImport } from './routes/blog/all'
import { Route as BlogBlogIdRouteImport } from './routes/blog/$blogId'
import { Route as LandingPageLandingPageRouteImport } from './routes/_landing-page/_landingPage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAllRoute = BlogAllRouteImport.update({
  id: '/blog/all',
  path: '/blog/all',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogBlogIdRoute = BlogBlogIdRouteImport.update({
  id: '/blog/$blogId',
  path: '/blog/$blogId',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingPageLandingPageRoute = LandingPageLandingPageRouteImport.update({
  id: '/_landing-page/_landingPage',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog/$blogId': typeof BlogBlogIdRoute
  '/blog/all': typeof BlogAllRoute
  '/about': typeof AboutIndexRoute
  '/blog': typeof BlogIndexRoute
  '/support': typeof SupportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog/$blogId': typeof BlogBlogIdRoute
  '/blog/all': typeof BlogAllRoute
  '/about': typeof AboutIndexRoute
  '/blog': typeof BlogIndexRoute
  '/support': typeof SupportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_landing-page/_landingPage': typeof LandingPageLandingPageRoute
  '/blog/$blogId': typeof BlogBlogIdRoute
  '/blog/all': typeof BlogAllRoute
  '/about/': typeof AboutIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/support/': typeof SupportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog/$blogId'
    | '/blog/all'
    | '/about'
    | '/blog'
    | '/support'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blog/$blogId' | '/blog/all' | '/about' | '/blog' | '/support'
  id:
    | '__root__'
    | '/'
    | '/_landing-page/_landingPage'
    | '/blog/$blogId'
    | '/blog/all'
    | '/about/'
    | '/blog/'
    | '/support/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LandingPageLandingPageRoute: typeof LandingPageLandingPageRoute
  BlogBlogIdRoute: typeof BlogBlogIdRoute
  BlogAllRoute: typeof BlogAllRoute
  AboutIndexRoute: typeof AboutIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  SupportIndexRoute: typeof SupportIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/': {
      id: '/support/'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/all': {
      id: '/blog/all'
      path: '/blog/all'
      fullPath: '/blog/all'
      preLoaderRoute: typeof BlogAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$blogId': {
      id: '/blog/$blogId'
      path: '/blog/$blogId'
      fullPath: '/blog/$blogId'
      preLoaderRoute: typeof BlogBlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing-page/_landingPage': {
      id: '/_landing-page/_landingPage'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LandingPageLandingPageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LandingPageLandingPageRoute: LandingPageLandingPageRoute,
  BlogBlogIdRoute: BlogBlogIdRoute,
  BlogAllRoute: BlogAllRoute,
  AboutIndexRoute: AboutIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  SupportIndexRoute: SupportIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
